Traceback (most recent call last):
  File "postprocess_90.py", line 18, in <module>
    output_dir = sys.argv[4]
IndexError: list index out of range
